### ISSUE TITLE
Build Partially Succeeded

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/navcontainerhelper#1645]
CI builds are giving a new result as of version 2.0.0. BCContainerHelper is now checking for compile warnings, and if any exist, issuing this as the pipeline result. The build completes, and you get your artifact and test results, but it still shows as Failed.

BCContainerHelper needs to pay attention to .vscode/project.ruleset.json when doing the compile.

![image](https://user-images.githubusercontent.com/31069850/105511320-c2a2c480-5c9d-11eb-9734-9b4f2ac3142a.png)

- does it happen all the time? Yes
- did it used to work? Yesterday (1.0.19)

**Comment by kylehardin6** [comment]
I was able to get a partial workaround accomplished using the -rulesetFile parameter. But I still get partially succeeded during the tests. I think Run-AlPipeline is respecting the rulesetFile parameter for the main alc compile, but not the test app compile.

**Comment by freddydk** [comment]
You can try to download a new Run-AlPipeline from here: https://raw.githubusercontent.com/microsoft/navcontainerhelper/dev/AppHandling/Run-AlPipeline.ps1

and overwrite the current file here:
C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.0\AppHandling\Run-AlPipeline.ps1

That should fix the test issue.

**Comment by freddydk** [comment]
2.0.1 will be released in a bit, where the behavior of Run-AlPipeline is reverted.
Now you need to specify -failOn 'warning' to fail the build on warnings and -failOn 'error' to fail on errors and partially succeed with warnings.

**Comment by kylehardin6** [comment]
failOn now works as advertised. Builds are back to succeeding even with warnings.

However, the test app compile still does not respect the rulesetFile parameter. The main app does, but not the test app.

**Comment by kylehardin6** [comment]
Not trying to stir in your soup, but it looks like none of the code in the if $app { section of Compiling Test Apps is being executed.

**Comment by freddydk** [comment]
Correct - things are either an $app or a $testapp.
Will have a look.

**Comment by freddydk** [comment]
Test apps are not build with cops and thus no ruleset applied.
