### ISSUE TITLE
Add switch GenerateSymbolReference to Compile-ObjectsInNavContainer.ps1

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#1709]
**Describe the issue**
Please can you add switch -GenerateSymbolReference to function Compile-ObjectsInNavContainer?
Thank you

**Comment by freddydk** [comment]
It is automatically applied if EnableSymbolLoadingAtServerStartup is enabled in customSettings,config but I have added the switch as well

**Comment by fridrichovsky** [comment]
Thank you. 

I tried EnableSymbols but container creation gets stuck. I assume it's related to a problem I've addressed with Microsoft before. They added parameter SuppressElevationCheck. First problem was that parameter allowed only "No","Yes" values. If you used function like Compile-NAVApplicationObject it gets stuck in different language then ENU. So Microsoft added new values "0" and "1". But they left the default value at "No" so the problem still remained. You can fix it by changing default value from "No" to "0" in C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1 or you have to allways use parameter SuppressElevationCheck 0 in all commads as Compile, Import, Export ....

I asked MS to solve this problem as well and I can confirm that it has been fixed by CU21.

**Comment by fridrichovsky** [comment]
I tried generate symbols manually and I set enable symbols after container creation, but I have problems. Can you help me as a person who has the greatest knowledge of the behavior of the BC container?

My problem is that I would like to use hybrid solution. Something is in C/AL and something in AL.
I created new onprem container in 14.18.x.x version (without enambled based on a previous comment)
I set EnableSymbolLoadingAtServerStartup and restart NST
I imported C/AL objects from TXT files to the container.
I recompiled all objects exlude MenuSuites. 
I started generate symbols for all objects exlude MenuSuites. 
When I try publish my AL to this container and I get many errors like this:
Codeunits/BillingPortalMgt.Codeunit.al(121,24): error AL0185: Table 'Web Sales Order' is missing
Pages/GenerateSegLeadsWizard.Page.al(180,51): error AL0185: Table 'Turnover Category' is missing

I don't know where is problem. If I connect to container with developmnet environment I can see all objects. I can compile all objects without error I can again start command for generate symbols which ends without error, but when I publish application I get error.
If I dowload symbols from this container I can't see new objects or changes from C/AL. 

I'm doing something wrong don't know about any settings what needs to be done? 

Thank you for your help

**Comment by freddydk** [comment]
Did you resolve this issue?

**Comment by fridrichovsky** [comment]
Hello,
unfortunately not.

**Comment by freddydk** [comment]
So adding the switch didn't solve the problem?
If you want my help on this, you will need to create a script I can run, which demonstrates the problem (including all)
I won't have time to reproduce this myself without a 100% repro scenario

**Comment by fridrichovsky** [comment]
Hello,
I am sorry for the delay. This is script which stucks (I was waiting 5 hours only :-) ). Problem is with -enableSymbolLoading.

New-BcContainer     -artifactUrl https://bcartifacts.azureedge.net/onprem/14.21.46103.0/cz
                    -containerName NYSNAV140DEV
                    -accept_eula
                    -accept_outdated
                    -updateHosts
                    -auth UserPassword
                    -licenseFile \\srv-license\D365BC140\Latest\license.flf
                    -Credential $Credential
                    -shortcuts StartMenu
                    -includeTestToolkit
                    -includeTestLibrariesOnly
                    -tenant
                    -alwaysPull
                    -additionalParameters --cpu-count 4 --dns=8.8.8.8 -e customnavsettings=ClientServicesMaxUploadSize=2000,MaxStreamReadSize=1000000000
                      --volume C:\Containers\NYSNAV140DEV\TempFiles:C:\Temp\TempFiles
                      --volume C:\Containers\NYSNAV140DEV\Agent:C:\Agent
                      --volume C:\Containers\NYSNAV140DEV\Packages:C:\Temp\Packages
                      --volume C:\Containers\NYSNAV140DEV\Backups:C:\Temp\Backups
                    -myScripts System.Collections.Hashtable
                    -multitenant:False
                    -enableTaskScheduler
		    -enableSymbolLoading
                    -ErrorAction Stop


Create container NYSNAV140DEV
BcContainerHelper is version 2.0.6
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 20H2
Docker Client Version is 20.10.2
Docker Server Version is 20.10.2
Removing NYSNAV140DEV from host hosts file
Removing NYSNAV140DEV-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\NYSNAV140DEV
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.19042.804
10.0.19042.804: Pulling from businesscentral
Digest: sha256:2aad7d7ccd948b12493778c18dbb7d5ce4b0f12e01af3bbea2b8ac2fcfea86d2
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19042.804
mcr.microsoft.com/businesscentral:10.0.19042.804
Using image mcr.microsoft.com/businesscentral:10.0.19042.804
Creating Container NYSNAV140DEV
Version: 14.19.45386.0-cz
Style: onprem
Multitenant: No
Platform: 14.0.45365.0
Generic Tag: 1.0.1.4
Container OS Version: 10.0.19042.804 (20H2)
Host OS Version: 10.0.19042.804 (20H2)
Using process isolation
Using locale cs-CZ
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file \\srv-license\D365BC140\Latest\license.flf
Additional Parameters:
--cpu-count 4 --dns=8.8.8.8 -e customnavsettings=ClientServicesMaxUploadSize=2000,MaxStreamReadSize=1000000000,EnableTaskScheduler=True
--volume C:\Containers\NYSNAV140DEV\TempFiles:C:\Temp\TempFiles
--volume C:\Containers\NYSNAV140DEV\Agent:C:\Agent
--volume C:\Containers\NYSNAV140DEV\Packages:C:\Temp\Packages
--volume C:\Containers\NYSNAV140DEV\Backups:C:\Temp\Backups
Files in C:\ProgramData\BcContainerHelper\Extensions\NYSNAV140DEV\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container NYSNAV140DEV from image mcr.microsoft.com/businesscentral:10.0.19042.804
e06845b054465a120463d2b7aa6d77efb077b05aac01cb79a9d2adc486822d1a
Waiting for container NYSNAV140DEV to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.19.45386.0/cz
Using installer from C:\Run\130
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
Changing Database Server Collation to Czech_100_CI_AS
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\CZ\RTC\RoleTailoredClient.Local.Cz.msi
Skipping C:\NAVDVD\Installers\CZ\WebHelp\WebHelp.Local.Cz.msi
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 61 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to ???????????????????????????????????????????????????????????????????????????????????????????????????192.168.2.1 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 192.168.2.170 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.170 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container
Hostname is NYSNAV140DEV
PublicDnsName is NYSNAV140DEV
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 50DC2E4600B6DBA7D0B760E952DF2D6974AE80C4
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting ClientServicesMaxUploadSize to 2000
Setting MaxStreamReadSize to 1000000000
Setting EnableTaskScheduler to True
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA                                                                                     
Creating Admin as SQL User and add to sysadmin                                                                          
Container Dns Name  : NYSNAV140DEV
Web Client          : http://NYSNAV140DEV/NAV/
Dev. Server         : http://NYSNAV140DEV
Dev. ServerInstance : NAV
Setting NYSNAV140DEV to 172.17.120.116 in host hosts file

Files:
http://NYSNAV140DEV:8080/ALLanguage.vsix

Container Total Physical Memory is 31.8Gb
Container Free Physical Memory is 15.2Gb

Initialization took 66 seconds
Ready for connections!
Reading CustomSettings.config from NYSNAV140DEV
Creating Desktop Shortcuts for NYSNAV140DEV
Importing Objects from C:\TestToolKit\CALTestLibraries.CZ.fob (container path)
Generating symbols
Adding SQL-Server credentials for authentication
Creating application symbols in NYSNAV140DEV

**Comment by fridrichovsky** [comment]
My second problem is with generate symbols. I tried prepare script for you so I hope that it will work to you. 
I tested it on my PC and I had same problem with symbols so it should work. I have objects in C/AL with object ID range 95100..95199. After symbols generate I don't see objects from metioned range in symbols.

Thank you for your help.

[Test.zip](https://github.com/microsoft/navcontainerhelper/files/6067174/Test.zip)

**Comment by freddydk** [comment]
I looked at the zip file.
Without the -enableSymbolLoading - you can generate symbols as many times as you want, the server will never use them.
I think we need to solve the -enableSymbolLoading first.

If I run this on my machine:
```
New-BcContainer -artifactUrl "https://bcartifacts.azureedge.net/onprem/14.21.46103.0/cz" `
                -containerName NYSNAV140DEV `
                -accept_eula `
                -updateHosts `
                -auth $auth `
                -licenseFile $licenseFile `
                -Credential $Credential `
                -includeTestToolkit `
                -includeTestLibrariesOnly `
                -enableTaskScheduler `
                -enableSymbolLoading
```
I get a container with symbols.
```
...
Files:
http://NYSNAV140DEV:8080/ALLanguage.vsix

Container Total Physical Memory is 63.8Gb
Container Free Physical Memory is 30.3Gb

Initialization took 114 seconds
Ready for connections!
Reading CustomSettings.config from NYSNAV140DEV
Creating Desktop Shortcuts for NYSNAV140DEV
Importing Objects from C:\TestToolKit\CALTestLibraries.CZ.fob (container path)
Generating symbols
Adding SQL-Server credentials for authentication
Creating application symbols in NYSNAV140DEV
[0] [04.03.21  7:14:03] The command completed successfully in '273' seconds.
Symbols successfully generated
TestToolkit successfully imported
Container NYSNAV140DEV successfully created
```
Could you try to run this exact command without any other parameters - just to see whether this completes?
Thanks

**Comment by fridrichovsky** [comment]
I tried your command but I have same problem. For me it does not work. I don't know if it is relevant information, but there are information about OS.
Language: Czech
Language for appliaction that does not support Unicode: Czech

**Comment by freddydk** [comment]
Yeah, I have no chance of setting up a Czech machine, sorry

If you could try the following, run this:
```
$auth = "UserPassword"
$credential = New-Object pscredential -ArgumentList 'admin', $passwordSecret.SecretValue
$licenseFile = 'your license file'
New-BcContainer -artifactUrl "https://bcartifacts.azureedge.net/onprem/14.21.46103.0/cz" `
                -containerName NYSNAV140DEV `
                -accept_eula `
                -updateHosts `
                -auth $auth `
                -licenseFile $licenseFile `
                -Credential $Credential `
                -enableTaskScheduler `
                -enableSymbolLoading
```
This should NOT generate symbols (due to another bug)
Then, in PowerShell ISE (not x86), use:
```
Enter-BcContainer NYSNAV140DEV
```
and paste this code into an editor window and press F5
```
$ProcessArguments = 'Command=generatesymbolreference, Database="CRONUS", ServerName="localhost\SQLEXPRESS", ntauthentication=0, username="admin", password="P@ssword1"'
$Process = Start-Process -FilePath "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe" -ArgumentList $ProcessArguments -PassThru
$process
```
What is the output of this?
if $process is empty, try to run
```
PSEDIT "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\naverrorlog.txt"
```
else run
```
$process | Wait-Process
```
and while this is running, open a NYSNAV140DEV PowerShell prompt (desktop icon) and run get-process to see whether the process runs?

**Comment by fridrichovsky** [comment]
I get this process 

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                                                                
-------  ------    -----      -----     ------     --  -- -----------                                                                                                                                                                
     48       6     1280       3912       0,05  16696  27 finsql 
 
$process | Wait-Process - Stucks

Processes in container during waiting                                                                                                                                 
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    100       6     1724       5332      32,02  24124  11 CExecSvc
     65       5     2028       4032       0,02  31464  11 cmd
     91       7     1156       5332       0,02    908  11 conhost
     93       7     1212       5532       0,22  27284  11 conhost
     93       7     1188       5508       0,11  30344  11 conhost
    320      13     1808       5188       5,45  49680  11 csrss
     31       5      764       3004       0,02  37784  11 fontdrvhost
      0       0       60          8                 0   0 Idle
   6995      22     9968      14868      16,53  48252  11 lsass
   1304     262  1025784     232800     166,88  40844  11 Microsoft.Dynamics.Nav.Server
    229      13     2736       8928       0,11  19176  11 msdtc
    669      32    92500     104488       2,23   6356  11 powershell
    497      32    76844      57836      39,14  19248  11 powershell
    689      30    63640      74600       2,39  22240  11 powershell
    242      10     2688       6804       3,94  39364  11 services
     50       3     1040       1768       0,08  34376   0 smss
    112      10     1448       5160       0,05  34224  11 sqlbrowser
    675    1122   500708     153412   5 180,73  52632  11 sqlservr
    140      10     1956       7644       0,05   1412  11 sqlwriter
    115       7     1320       5584       0,03   5696  11 svchost
    109       8     1308       5628       0,02  12504  11 svchost
    145       9     1736       6392       0,06  16312  11 svchost
    185      13     2968       8476       2,14  17388  11 svchost
    346      15     3256       8924       4,89  31560  11 svchost
    414      16     8304      12920      15,72  36848  11 svchost
    822      32    11432      23640      20,63  36884  11 svchost
    540      24    19404      32792      22,14  40268  11 svchost
    240      15     5244       9980       0,67  40528  11 svchost
    613      35     6624      18284      18,16  43116  11 svchost
    168      12     4248       8632       0,19  48924  11 svchost
    339      13     3116      10336       1,22  50448  11 svchost
  55358       0      208       2044   6 575,53      4   0 System
    219      17     4876      10344       1,44  19560  11 w3wp
    171      11     1648       6980       0,11  38220  11 wininit

**Comment by freddydk** [comment]
It looks like finsql is not running while it is waiting for the process.
Could you try 
PSEDIT "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\naverrorlog.txt"

Is there an error log?

**Comment by fridrichovsky** [comment]
It have similar behavior as I described with SuppressElevationCheck  parameter, but there where finsql.exe process between processes (with 0% CPU usage).

**Comment by fridrichovsky** [comment]
there is no errors
Cannot find path 'C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\naverrorlog.txt' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (C:\Program File...naverrorlog.txt:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by freddydk** [comment]
And if you add the Suppresselevationcheck parameter:
```
$ProcessArguments = 'Command=generatesymbolreference, Database="CRONUS", ServerName="localhost\SQLEXPRESS", ntauthentication=0, username="admin", password="yourpassword", SuppressElevationCheck=0'
$Process = Start-Process -FilePath "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe" -ArgumentList $ProcessArguments -PassThru
$process
```

does that change anything?

**Comment by freddydk** [comment]
You could also exit from the enter-bccontainer and use
get-bccontainereventlog to see if there is anything in the eventlog that could describe this problem?

**Comment by fridrichovsky** [comment]
I do not see something relevant, but I tried one thing. I started compile commad again and I have error in naverrorlog now (bellow). It looks that NST think that compilation is running. 

[22926090] The Object Metadata table cannot be changed because it is locked by another user. This can be caused by one of the following tasks:

* Objects are being compiled.
* Table schema is synchronizing.
* Objects are being imported.

Wait until the user is finished and then try again.

**Comment by freddydk** [comment]
Well, that might be the symbol generation that is locking the object metadata table.
Did you try the eventlog?

**Comment by fridrichovsky** [comment]
Yes I did, I had to find english translations because event log is in Czech language :-)

There are many warnings
ERROR_FT_WRITE_RECOVERY

    705 (0x2C1)

    {Redundant Write} To satisfy a write request, the NT fault-tolerant file system successfully wrote a redundant copy of the information. This was done because the file system encountered a failure on a member of the fault-tolerant volume, but was not able to reassign the failing area of the device.

And some errors
ERROR_RXACT_STATE_CREATED

    701 (0x2BD)

    This informational level status indicates that a specified registry sub-tree transaction state did not yet exist and had to be created.

**Comment by freddydk** [comment]
I have never seen the write-recovery things before - that is strange.
Any details on the 701?

**Comment by fridrichovsky** [comment]
I tried create container again. These errors I get (first error is first from cotnainer createion):
Source: **CertificateServicesClient-CertEnroll** --> Provide Microsoft Passport Key Storage Provider was not loaded, because inicialziation failed. 
Source: **Security-SPP** --> Data about hardware can't be collecte. Error code:0xD0000034
Source: **MicrosoftDynamicsNavServer$NAV** -->  Invalid object name 'master.dbo.$ndo$srvproperty'.
  Command SQL:
  SELECT license FROM [master].[dbo].[$ndo$srvproperty]
  StackTrace:
 Source: **MicrosoftDynamicsNavServer$NAV** --> Warnings about redundant write
 Source: **MicrosoftDynamicsNavServer$NAV** --> Error 701 there is now detail information

If I start compilation it generete new events:
 Source: **MicrosoftDynamicsNavServer$NAV** --> Warnings about redundant write
 Source: **MicrosoftDynamicsNavServer$NAV** --> Error 701 there is now detail information

I tested another container that we use and there are same warnings and errors. Strange is taht NAV wroks and everything looks OK. So I don't know if these warnings and errors are important.

**Comment by fridrichovsky** [comment]
Hi freddy,
It looks that I solved my problem. I can't use switch -enableSymbolLoading, but I can change settings for NST in container through your function Invoke-ScriptInBCContainer. 
So I create container without problematic switch. I have to recompile all objects and after that I have to recompile objects with generate symbols. I don't know what is different but this works for me. So I am happy now and I suppose that you can leave this issue (it is old BC version so who cares ;-) )
Thank you for your support to me.

**Comment by freddydk** [comment]
Thanks, will close this one.
