### ISSUE TITLE
Error Run-AlValidation validateNextMajor

### ISSUE THREAD

**Issue by mishof** [microsoft/navcontainerhelper#3525]
When we check our apps using Run-AlValidation with validateNextMajor set,
we keep getting the same error. This started happening when the NextMajor became
25. It seems the runtime is being confused with the major number.
Runtime could only be like 13 or 14.

**Scripts used to create container and cause the issue**
```
                    Run-AlValidation `
                        -validateNextMajor `
                        -apps $Appfile.FullName `
                        -installApps $installApps `
                        -countries $Countries `
                        -supportedCountries $Countries `
                        -affixes $Affixes `
                        -throwOnError `
                        -skipVerification 
```

**Full output of scripts**
```
2024-04-29T22:33:17.0351477Z Creating container for country nl
2024-04-29T22:33:17.1879046Z BcContainerHelper is version 6.0.17-preview1194
2024-04-29T22:33:17.1883636Z BcContainerHelper is running as administrator
2024-04-29T22:33:17.1995179Z HyperV is Enabled
2024-04-29T22:33:17.2001476Z Host is Microsoft Windows Server 2022 Datacenter - 10.0.20348.2402
2024-04-29T22:33:17.2002192Z UsePsSession is True
2024-04-29T22:33:17.2005254Z UsePwshForBc24 is True
2024-04-29T22:33:17.2005859Z UseWinRmSession is allow
2024-04-29T22:33:17.2006329Z UseSslForWinRmSession is True
2024-04-29T22:33:17.4726483Z Docker Client Version is 24.0.7
2024-04-29T22:33:17.4738238Z Docker Server Version is 24.0.7
2024-04-29T22:33:17.6339252Z Removing Desktop shortcuts
2024-04-29T22:33:17.6871230Z Downloading artifact /sandbox/25.0.19026.0/nl
2024-04-29T22:33:17.6912082Z Downloading C:\Users\VssAdministrator\AppData\Local\Temp\313860f0-b26c-484f-9b48-bd4929d70315.zip
2024-04-29T22:33:36.4031952Z Unpacking artifact to tmp folder using 7zip
2024-04-29T22:33:52.3737779Z Fetching all docker images
2024-04-29T22:33:52.6856215Z Fetching all docker volumes
2024-04-29T22:33:52.8172952Z Using image mcr.microsoft.com/businesscentral:ltsc2022-filesonly-dev
2024-04-29T22:33:53.2437569Z Creating Container bcserver
2024-04-29T22:33:53.2449910Z Style: sandbox
2024-04-29T22:33:53.2460745Z Multitenant: Yes
2024-04-29T22:33:53.2472793Z Version: 25.0.19026.0
2024-04-29T22:33:53.2482304Z Platform: 25.0.18934.0
2024-04-29T22:33:53.2498980Z Generic Tag: 1.0.2.20-dev
2024-04-29T22:33:53.2517520Z Container OS Version: 10.0.20348.2402 (ltsc2022)
2024-04-29T22:33:53.2532965Z Host OS Version: 10.0.20348.2402 (ltsc2022)
2024-04-29T22:33:53.2580089Z Using process isolation
2024-04-29T22:33:53.2604555Z Using locale nl-NL
2024-04-29T22:33:53.2636950Z Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
2024-04-29T22:33:53.3304934Z Additional Parameters:
2024-04-29T22:33:53.3322979Z --expose 5986
2024-04-29T22:33:53.3338654Z --env customNavSettings=EnableTaskScheduler=True
2024-04-29T22:33:53.3357313Z Files in C:\ProgramData\BcContainerHelper\Extensions\bcserver\my:
2024-04-29T22:33:53.3385669Z - AdditionalOutput.ps1
2024-04-29T22:33:53.3404619Z - AdditionalSetup.ps1
2024-04-29T22:33:53.3417750Z - HelperFunctions.ps1
2024-04-29T22:33:53.3432934Z - MainLoop.ps1
2024-04-29T22:33:53.3446713Z - SetupVariables.ps1
2024-04-29T22:33:53.3506508Z - updatehosts.ps1
2024-04-29T22:33:53.3520490Z Creating container bcserver from image mcr.microsoft.com/businesscentral:ltsc2022-filesonly-dev
2024-04-29T22:33:53.7811046Z b6d055f30175acc988b737a931a71d3e550dd25be3e5d8a6e5bb15805a99c265
2024-04-29T22:33:56.9022579Z Waiting for container bcserver to be ready
2024-04-29T22:34:12.8899284Z Using artifactUrl https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19026.0/nl
2024-04-29T22:34:12.8902350Z Using installer from C:\Run\240
2024-04-29T22:34:12.8904825Z Installing Business Central: multitenant=True, installOnly=False, filesOnly=True, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\sandbox\25.0.19026.0\nl, platformArtifactPath=c:\dl\sandbox\25.0.19026.0\platform, databasePath=c:\dl\sandbox\25.0.19026.0\nl\BusinessCentral-NL.bak, licenseFilePath=c:\dl\sandbox\25.0.19026.0\nl\Cronus.bclicense, rebootContainer=True
2024-04-29T22:34:12.8909680Z Installing from artifacts
2024-04-29T22:34:12.8913401Z Copying Service Tier Files
2024-04-29T22:34:12.8913849Z c:\dl\sandbox\25.0.19026.0\platform\ServiceTier\Program Files
2024-04-29T22:34:12.8914285Z c:\dl\sandbox\25.0.19026.0\platform\ServiceTier\System64Folder
2024-04-29T22:34:12.8916113Z Copying Web Client Files
2024-04-29T22:34:32.4427492Z c:\dl\sandbox\25.0.19026.0\platform\WebClient\Microsoft Dynamics NAV
2024-04-29T22:34:32.4427954Z Copying ModernDev Files
2024-04-29T22:34:32.4428127Z c:\dl\sandbox\25.0.19026.0\platform
2024-04-29T22:34:32.4428341Z c:\dl\sandbox\25.0.19026.0\platform\ModernDev\program files\Microsoft Dynamics NAV
2024-04-29T22:34:32.4428523Z Copying additional files
2024-04-29T22:34:32.4428691Z Copying ConfigurationPackages
2024-04-29T22:34:32.4428906Z C:\dl\sandbox\25.0.19026.0\nl\ConfigurationPackages
2024-04-29T22:34:32.4429087Z Copying Test Assemblies
2024-04-29T22:34:32.4429246Z C:\dl\sandbox\25.0.19026.0\platform\Test Assemblies
2024-04-29T22:34:32.4429422Z Copying Extensions
2024-04-29T22:34:32.4429593Z C:\dl\sandbox\25.0.19026.0\nl\Extensions
2024-04-29T22:34:32.4429762Z Copying Applications
2024-04-29T22:34:32.4429918Z C:\dl\sandbox\25.0.19026.0\platform\Applications
2024-04-29T22:34:32.4430096Z Copying Applications.NL
2024-04-29T22:34:32.4430273Z C:\dl\sandbox\25.0.19026.0\nl\Applications.NL
2024-04-29T22:34:32.4430464Z Copying dependencies
2024-04-29T22:34:32.4430608Z Importing PowerShell Modules
2024-04-29T22:34:32.4430784Z Skipping restore of Cronus database
2024-04-29T22:34:32.4430982Z Modifying Business Central Service Tier Config File for Docker
2024-04-29T22:34:32.4431758Z Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
2024-04-29T22:34:32.4431958Z Installation took 32 seconds
2024-04-29T22:34:32.4433048Z Installation complete
2024-04-29T22:34:32.4502954Z Ready for connections!
2024-04-29T22:35:18.2971858Z Reading CustomSettings.config from bcserver
2024-04-29T22:36:47.0461200Z Cleanup old dotnet core assemblies
2024-04-29T22:37:31.6493991Z 
2024-04-29T22:37:31.6500064Z Creating container took 255 seconds
2024-04-29T22:37:31.6613209Z   _____                   _                                    _____                           _____            
2024-04-29T22:37:31.6613696Z  |  __ \                 (_)                 /\               / ____|                         / ____|           
2024-04-29T22:37:31.6614273Z  | |__) |   _ _ __  _ __  _ _ __   __ _     /  \   _ __  _ __| (___   ___  _   _ _ __ ___ ___| |     ___  _ __  
2024-04-29T22:37:31.6615128Z  |  _  / | | | '_ \| '_ \| | '_ \ / _` |   / /\ \ | '_ \| '_ \\___ \ / _ \| | | | '__/ __/ _ \ |    / _ \| '_ \ 
2024-04-29T22:37:31.6615364Z  | | \ \ |_| | | | | | | | | | | | (_| |  / ____ \| |_) | |_) |___) | (_) | |_| | | | (__  __/ |____ (_) | |_) |
2024-04-29T22:37:31.6615605Z  |_|  \_\__,_|_| |_|_| |_|_|_| |_|\__, | /_/    \_\ .__/| .__/_____/ \___/ \__,_|_|  \___\___|\_____\___/| .__/ 
2024-04-29T22:37:31.6615837Z                                    __/ |          | |   | |                                              | |    
2024-04-29T22:37:31.6621064Z                                   |___/           |_|   |_|                                              |_|    
2024-04-29T22:37:35.2421090Z Downloading AL Language Extension to C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.971907.zip
2024-04-29T22:37:39.2085758Z using 7zip
2024-04-29T22:37:52.9554641Z Run-AlCops Telemetry Correlation Id: d3210df4-c211-489e-af1d-0ee7b2a467d8
2024-04-29T22:37:53.1220187Z Unexpected error while validating app. Error is: Unknown platform version: 25.0
2024-04-29T22:37:53.1221121Z 
2024-04-29T22:37:53.1221806Z ExitCode: 1
2024-04-29T22:37:53.1222512Z Commandline: C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.971907\extension\bin\win32\altool.exe GetLatestSupportedRuntimeVersion 25.0
2024-04-29T22:37:53.1239226Z at CmdDo, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\HelperFunctions.ps1: line 120
2024-04-29T22:37:53.1239623Z at RunAlTool, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\HelperFunctions.ps1: line 1242
2024-04-29T22:37:53.1242928Z at Run-AlCops, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlCops.ps1: line 126
2024-04-29T22:37:53.1243737Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlValidation.ps1: line 475
2024-04-29T22:37:53.1244608Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlValidation.ps1: line 454
2024-04-29T22:37:53.1245358Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlValidation.ps1: line 397
2024-04-29T22:37:53.1250289Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlValidation.ps1: line 361
2024-04-29T22:37:53.1252758Z at Run-AlValidation, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlValidation.ps1: line 359
2024-04-29T22:37:53.1254498Z at <ScriptBlock>, D:\a\_temp\afb7fd1d-5ecc-4e39-b979-66eab72e7174.ps1: line 14
2024-04-29T22:37:53.1255164Z at <ScriptBlock>, <No file>: line 1
2024-04-29T22:37:53.1276586Z 
2024-04-29T22:37:53.1277019Z   _____                           _                _____            _        _                 
2024-04-29T22:37:53.1277617Z  |  __ \                         (_)              / ____|          | |      (_)                
2024-04-29T22:37:53.1280236Z  | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
2024-04-29T22:37:53.1286594Z  |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
2024-04-29T22:37:53.1286859Z  | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |   
2024-04-29T22:37:53.1287030Z  |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
2024-04-29T22:37:53.1287219Z                                            __/ |                                               
2024-04-29T22:37:53.1287378Z                                           |___/                                                
2024-04-29T22:37:53.1287664Z 
2024-04-29T22:37:53.7090318Z Removing Session bcserver
2024-04-29T22:37:53.7091133Z Removing container bcserver
2024-04-29T22:37:54.7157932Z Removing entries from hosts
2024-04-29T22:37:54.8070805Z Removing bcserver from container hosts file
2024-04-29T22:37:54.9283633Z Removing bcserver-* from container hosts file
2024-04-29T22:37:54.9558917Z Removing Desktop shortcuts
2024-04-29T22:37:55.0531784Z Removing C:\ProgramData\BcContainerHelper\Extensions\bcserver
2024-04-29T22:37:55.0559501Z 
2024-04-29T22:37:55.0564969Z Removing container took 2 seconds
2024-04-29T22:37:55.0580149Z 
2024-04-29T22:37:55.0583342Z AL Validation finished in 308 seconds
2024-04-29T22:37:55.0595747Z  __      __   _ _     _       _   _               _____                _ _       
2024-04-29T22:37:55.0596126Z  \ \    / /  | (_)   | |     | | (_)             |  __ \              | | |      
2024-04-29T22:37:55.0596400Z   \ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__) |___ ___ _   _| | |_ ___ 
2024-04-29T22:37:55.0597413Z    \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  _  // _ \ __| | | | | __/ __|
2024-04-29T22:37:55.0598574Z     \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | \ \  __\__ \ |_| | | |_\__ \
2024-04-29T22:37:55.0599637Z      \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \_\___|___/\__,_|_|\__|___/
2024-04-29T22:37:55.0603828Z 
2024-04-29T22:37:55.0641352Z Unexpected error while validating app. Error is: Unknown platform version: 25.0
2024-04-29T22:37:55.0641552Z 
2024-04-29T22:37:55.0641739Z ExitCode: 1
2024-04-29T22:37:55.0643700Z Commandline: C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.971907\extension\bin\win32\altool.exe GetLatestSupportedRuntimeVersion 25.0
2024-04-29T22:37:55.0650237Z   _____                          ___      __   _ _     _       _   _               ______    _ _                
2024-04-29T22:37:55.0650661Z  |  __ \                   /\   | \ \    / /  | (_)   | |     | | (_)             |  ____|  (_) |               
2024-04-29T22:37:55.0650920Z  | |__) |   _ _ __ ______ /  \  | |\ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__ __ _ _| |_   _ _ __ ___ 
2024-04-29T22:37:55.0652840Z  |  _  / | | | '_ \______/ /\ \ | | \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  __/ _` | | | | | | '__/ _ \
2024-04-29T22:37:55.0653088Z  | | \ \ |_| | | | |    / ____ \| |  \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | | (_| | | | |_| | | |  __/
2024-04-29T22:37:55.0653267Z  |_|  \_\__,_|_| |_|   /_/    \_\_|   \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \__,_|_|_|\__,_|_|  \___|
2024-04-29T22:37:55.0660482Z 
2024-04-29T22:37:55.4436003Z Run-AlValidation Telemetry Correlation Id: 30755df9-dcd2-4350-9da1-51bbb5c201e4
2024-04-29T22:37:55.5171905Z Unexpected error while validating app. Error is: Unknown platform version: 25.0
2024-04-29T22:37:55.5173024Z ExitCode: 1
2024-04-29T22:37:55.5173398Z Commandline: C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.971907\extension\bin\win32\altool.exe 
2024-04-29T22:37:55.5173978Z GetLatestSupportedRuntimeVersion 25.0
2024-04-29T22:37:55.5181172Z At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlValidation.ps1:547 char:5
2024-04-29T22:37:55.5182042Z +     throw ($validationResult -join "`n")
2024-04-29T22:37:55.5182221Z +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-04-29T22:37:55.5187444Z     + CategoryInfo          : OperationStopped: (Unexpected erro...imeVersion 25.0:String) [], RuntimeException
2024-04-29T22:37:55.5187794Z     + FullyQualifiedErrorId : Unexpected error while validating app. Error is: Unknown platform version: 25.0
2024-04-29T22:37:55.5188017Z ExitCode: 1
2024-04-29T22:37:55.5188436Z     Commandline: C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.971907\extension\bin\win32\altool.exe GetLa 
2024-04-29T22:37:55.5188655Z    testSupportedRuntimeVersion 25.0
2024-04-29T22:37:55.5188819Z  
2024-04-29T22:37:56.2639983Z ##[error]PowerShell exited with code '1'.
2024-04-29T22:37:56.4509117Z ##[section]Finishing: PowerShell
```

NavContainerHelper is version 6.0.17-preview1194
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2022 Datacenter 
Docker Client Version is 24.0.7
Docker Server Version is 24.0.7

It happens all the time now.
It used to work until a few weeks ago.

**Comment by esbenk** [comment]
It must be the wrong version of the altool being used. I have justed with the altool.exe from v14.0.986719 (pre-release) from the marketplace. It works fine.  25.0 -> 14.0.

**Comment by freddydk** [comment]
OK, will investigate which tool is used.

**Comment by freddydk** [comment]
By default, Run-AlValidation will always grab the latest AL Language Extension from the marketplace.
When running validation against next major - it should use the AL Language Extension included in the artifacts instead.
You should be able to specify `-vsixFile "preview"` when running Run-AlValidation today to use the pre-release version, which should work now.

**Comment by mishof** [comment]
Thanks! I added it to our daily testing routine.
When we test for next major we use the latest
preview version of container helper. 
So the "preview" setting fits right in that philosophy.
If the workaround isn't there tonight, 
it will pop up when the next containerhelper preview version is out.
There is no hurry, BC25 is still a long way ahead of us.

**Comment by mishof** [comment]
It accepts the new "preview" parameter, but the error remains

2024-05-02T03:07:38.7937980Z BcContainerHelper version 6.0.17

2024-05-02T03:26:20.1797137Z  |  __ \                             | |               
2024-05-02T03:26:20.1797461Z  | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___ 
2024-05-02T03:26:20.1797964Z  |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
2024-05-02T03:26:20.1798156Z  | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
2024-05-02T03:26:20.1798379Z  |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/
2024-05-02T03:26:20.1798455Z 
2024-05-02T03:26:20.1808846Z Container name                  bcserver
2024-05-02T03:26:20.1997704Z Credential                      admin/Qoma9123
2024-05-02T03:26:20.2061081Z MemoryLimit                     8G
2024-05-02T03:26:20.2072470Z validateVersion                 
2024-05-02T03:26:20.2088441Z validateCurrent                 False
2024-05-02T03:26:20.2104289Z validateNextMinor               False
2024-05-02T03:26:20.2118889Z validateNextMajor               True
2024-05-02T03:26:20.2137128Z countries                       nl
2024-05-02T03:26:20.2153234Z validateCountries               nl
2024-05-02T03:26:20.2169089Z affixes                         x
2024-05-02T03:26:20.2183119Z supportedCountries              nl
2024-05-02T03:26:20.2195223Z ObsoleteTagMinAllowedMajorMinor 
2024-05-02T03:26:20.2210165Z vsixFile                        preview
2024-05-02T03:26:20.2218942Z Install Apps
2024-05-02T03:26:20.2226062Z - None
2024-05-02T03:26:20.2233305Z Previous Apps
2024-05-02T03:26:20.2247475Z - None
2024-05-02T03:26:20.2247822Z Apps

2024-05-02T03:31:55.7895000Z Unexpected error while validating app. Error is: Unknown platform version: 25.0
2024-05-02T03:31:55.7895177Z 
2024-05-02T03:31:55.7895395Z ExitCode: 1
2024-05-02T03:31:55.7895852Z Commandline: C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.971907\extension\bin\win32\altool.exe GetLatestSupportedRuntimeVersion 25.0

**Comment by freddydk** [comment]
Yeah - I found the bug - it's on my site - will provide a fix asap.

**Comment by MODUSCarstenScholling** [comment]
Hey Freddy,

the same happens using Run-AlCops. But this cmd does not provide a parameter for vsix selection. Stops with the following call stack:

```PS
Downloading AL Language Extension to C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.1007491.zip
using 7zip
Run-AlCops Telemetry Correlation Id: 15150e49-1dec-4bf8-9910-8458b81d9aae

[Removing removed]

Unknown platform version: 25.0

ExitCode: 1
Commandline: C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.1007491\extension\bin\win32\altool.exe GetLatestSupportedRuntimeVersion 25.0 at CmdDo, C:\Users\SuperUser\Documents\PowerShell\Modules\BcContainerHelper\6.0.17\HelperFunctions.ps1: line 120
at RunAlTool, C:\Users\SuperUser\Documents\PowerShell\Modules\BcContainerHelper\6.0.17\HelperFunctions.ps1: line 1242
at Run-AlCops, C:\Users\SuperUser\Documents\PowerShell\Modules\BcContainerHelper\6.0.17\AppHandling\Run-AlCops.ps1: line 126
at <ScriptBlock>, C:\BcBuild\SuperDir\execute.ps1: line 967
```

**Comment by freddydk** [comment]
The vsixFile parameter also didn't fix the problem.
There will be a fix in the next preview

**Comment by freddydk** [comment]
Shipped in preview just now

**Comment by freddydk** [comment]
@vlnzr please don't reply to closed issues, create a new issue if you have something we need to look at
