### ISSUE TITLE
Don't overwrite .nupkg contents if the name is the same

### ISSUE THREAD

**Issue by hemisphera** [microsoft/navcontainerhelper#3889]
**Describe the issue**
Using `Download-BcNugetPackageToFolder` overwrites the `.app`-files contained in the `.nupkg` if they have the same name. 

Suggestion: when copying the extracted contents of the main package and all its subpackages, if a file with that name already exists, append the appId to the filename. This avoids overwriting the files, if multiple different packages/dependencies happen to have the same filename within the `.nupkg`.

**Comment by freddydk** [comment]
Fixed in the latest preview

**Comment by lktraser** [comment]
Hi @hemisphera, this is causing some issues for us as we also use NuGet for Runtime packages and want the extra naming schema for those as they are generated in Runtime Conversion example: "TRASER Software GmbH_TRASER Storage_2302.241100.20250425.1_RUNTIME-23.2-w1.app"

It would be better if this renaming of the NuGet package contents were optional. Sadly we still don't have any meta-data in the app package for it's runtime creation version and locale so we only have the name as an option.
