### ISSUE TITLE
Run-TestsInBCContainer Hanging When Using ExtensionId

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/navcontainerhelper#717]
I've created a container from mcr.microsoft.com/businesscentral/sandbox, published my extension and am running tests in the container with the following:

Run-TestsInBCContainer -containerName bc -companyName 'My Company' -credential (Get-Credential) -extensionId af44e35f-7ce0-4e9c-bf96-975316143aac

On first opening a PowerShell session this works as expected. Running the same command in the same session seems to hang (I've left it for 20 mins or so - it seems like it is never going to finish). If I cancel the command with Ctrl+C then run it again it works. Running a third time will hang until cancelled.

This seems to be limited to using the -extensionId parameter. I can repeatedly run the tests without that parameter with the same tests in the same container fine.

Opening the AL Test Tool in the client I can see that, on the times it hangs, that the test suite is loaded with the right codeunits and methods but doesn't seem to run them (or at least get as far as reporting the results).

**Comment by freddydk** [comment]
The bug is in the test page.
When opening 130455, adding the extensionid and running the test - they run
Close the page and If you open 130455 again, adding the same extensionid you get a validation error on the page. The PowerShell test runner didn't take this into account and hang.
Next version, it will fail (until we have fixed the error in the page)

**Comment by freddydk** [comment]
Shipped in 0.6.4.18

**Comment by jimmymcp** [comment]
Hi,

Was the intention of this change that Run-TestsInBCContainer would error rather than sticking in a loop? I'm still getting a (seemingly) non-responsive PowerShell session when running the function a second time (same repro as above).

I'm using navcontainerhelper 0.6.4.18

Any ideas?

**Comment by freddydk** [comment]
As explained, the bug is in the app- nothing I can fix. The endless loop was just hiding the bug

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: James Pearson <notifications@github.com>
Sendt: Monday, November 11, 2019 12:33:16 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; State change <state_change@noreply.github.com>
Emne: Re: [microsoft/navcontainerhelper] Run-TestsInBCContainer Hanging When Using ExtensionId (#717)


Hi,

Was the intention of this change that Run-TestsInBCContainer would error rather than sticking in a loop? I'm still getting a (seemingly) non-responsive PowerShell session when running the function a second time (same repro as above).

I'm using navcontainerhelper 0.6.4.18

Any ideas?

**Comment by jimmymcp** [comment]
Yes, but I thought you were saying we'd see the bug now, not the endless loop?

**Comment by freddydk** [comment]
Did you restart ps and recreate the container?

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: James Pearson <notifications@github.com>
Sendt: Monday, November 11, 2019 12:48:39 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; State change <state_change@noreply.github.com>
Emne: Re: [microsoft/navcontainerhelper] Run-TestsInBCContainer Hanging When Using ExtensionId (#717)


Yes, but I thought you were saying we'd see the bug now, not the endless loop?

**Comment by jimmymcp** [comment]
Thanks - works/errors with a new container.
